media:
  input: public/images
content:
  - name: about
    label: About page
    type: file
    path: src/pages/about.astro
    fields:
      - { name: layout, type: string, hidden: true, default: layouts/base.njk }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/images } }