media: public/images
content:
  - name: pages
    label: Pages
    type: file
    path: src/pages/about.md
    fields:
      - name: title
        label: Title
        type: string
      - { name: body, label: Body, type: rich-text }
  - name: config
    label: Home Page Settings
    type: file
    path: page-settings.yml
    fields:
      - name: services
        label: Services
        type: object
        list: true
        fields:
         - name: title
           label: Title
           type: string
         - name: description
           label: Description
           type: string
