media: public/images
content:
  - name: pages
    label: Pages
    type: file
    path: src/pages/aboutus.md
    fields:
      - name: title
        label: Title
        type: string
      - { name: body, label: Body, type: rich-text }
        
        

        
        
