media:
  input: public/images
  output: /images
  
content:
  - name: config
    label: Home Page
    type: file
    path: page-settings.yml
    fields:
      - name: hero
        label: Hero
        type: object
        fields:
          - name: heading
            label: Heading
            type: string
            
          - name: button1
            label: Call to Action Button 1
            type: object
            fields:
              - name: text
                label: Text
                type: string
              - name: link
                label: Link
                type: string
                
          - name: button2
            label: Call to Action Button 2
            type: object
            fields:
              - name: text
                label: Text
                type: string
              - name: link
                label: Link
                type: string
                
      - name: services
        label: Services
        type: object
        list: true
        fields:
          - name: title
            label: false
            type: string
            
      - name: clients
        label: Select Clients
        type: object
        list: true
        fields:
          - name: name
            label: Client Name
            type: string
            
          - name: logo
            label: Logo
            type: image
            options:
              path: public/images/logos
              extensions: [jpg, jpeg, png, webp, svg]

  - name: about-pages
    label: About Page
    type: file
    path: src/pages/about.md
    fields:
      - name: title
        label: Title
        type: string
      - { name: body, label: Body, type: rich-text }              
