hero:
  heading: Strategy & technology solutions that help our clients solve their most important challenges

  button1:
    text: Get in Touch
    link: /contact

  button2:
    text: State-Based Marketplace
    link: /state-based-marketplace

services:
  - title: Management Consulting
  - title: Software Development
  - title: Data Integration
  - title: DevOps & Cloud

clients:
  - name: DC Health Link
    logo: /images/logos/dc-healthlink-logo.webp
  - name: DC.gov
    logo: /images/logos/dc-gov.webp
  - name: Connect for Health Colorado
    logo: /images/logos/connect-health-colorado.webp
  - name: MA Health Connector
    logo: /images/logos/massachusetts-health-connector.webp
  - name: FEMA
    logo: /images/logos/fema.webp
  - name: Pennsylvania DHS
    logo: /images/logos/pennsylvania-department-human-services.webp
  - name: Maryland DOH
    logo: /images/logos/maryland-department-health.webp
  - name: Montgomery County
    logo: /images/logos/montgomery-county-maryland.webp
  - name: SHVS
    logo: /images/logos/state-health-value-strategies.webp
  - name: Vermont Health Connect
    logo: /images/logos/vermont-health-connect.webp
  - name: DoDEA
    logo: /images/logos/dodea.webp
  - name: RWJF
    logo: /images/logos/robert-wood-johnson-foundation.webp
