services:
  - title: Management Consulting
    description: ''
  - title: Software Development
    description: ''
  - title: Data Integration
    description: ''
  - title: DevOps & Cloud
    description: ''

clients:
  - name: DC Health Link
    logo: /images/logos/dc-healthlink-logo.webp
  - name: DC.gov
    logo: /images/logos/dc-gov.webp
  - name: Connect for Health Colorado
    logo: /images/logos/connect-health-colorado.webp
  - name: MA Health Connector
    logo: /images/logos/massachusetts-health-connector.webp
  - name: FEMA
    logo: /images/logos/fema.webp
  - name: Pennsylvania DHS
    logo: /images/logos/pennsylvania-department-human-services.webp
  - name: Maryland DOH
    logo: /images/logos/maryland-department-health.webp
  - name: Montgomery County
    logo: /images/logos/montgomery-county-maryland.webp
  - name: SHVS
    logo: /images/logos/state-health-value-strategies.webp
  - name: Vermont Health Connect
    logo: /images/logos/vermont-health-connect.webp
  - name: DoDEA
    logo: /images/logos/dodea.webp
  - name: RWJF
    logo: /images/logos/robert-wood-johnson-foundation.webp
